### ISSUE TITLE
JudiJacobian

### ISSUE THREAD

**Issue by seaninho94** [slimgroup/JUDI.jl#73]
Is it possible to visualize the Jacobian operator in its matrix form? I can only see the data, which is a JudiVector but i cannot see the Jacobian or Forward operator.

Thank you!

**Comment by mloubout** [comment]
These operator are matrix free, i.e. they only have an action `F*q, J*dm, ...`. The matrix itself is never created as it would be way to big and unmanageable. 
Why do you want these as dense matrices?

**Comment by seaninho94** [comment]
There is no way to see the numerical values of the Jacobian matrix? I know that usually is too big but i'm using a small model.

Thank you

**Comment by mloubout** [comment]
There are no numerical values in our operators. They are linear operators that have defined behavior for a matrix-vector product they do not hold any value. 
There is no mechanism to transform our operators into a dense matrix neither for two reasons:
- they rely on [Devito](https://github.com/devitocodes/devito) that generates code at runtime for the wave-equation.
- the framework is based on abstract types rather than pure vectors (i.e judiVector) so you cannot just multiply it with the identity matrix.

But our operators are fully defined for LSQR or such so access to the values shouldn't be necessary,

**Comment by ziyiyin97** [comment]
If you @seaninho94 insist to look at the numerical values, you can do

``J_{ij}=e_i^T J e_j``

**Comment by seaninho94** [comment]
Thank you very much!
